# General Params
BINSIZE: 5 # ms - bin size for resampling
LAG: 100 # ms - how much to delay the kinematics by
SMOOTH_SD: 40 # ms - std of gaussian kernel for smoothing
DATASET: 'mc_maze_large' # NLB name of dataset

# W&B Params
WANDB_BASE_PROJECT: 'quant_neuro_final' # name of wandb project
WANDB_ENTITY: 'domenick-m' # wandb username (change to yours)

# Linear Model Params
RIDGE_ALPHAS: [0.0001, 0.001, 0.01, 0.1, 1, 10, 100] # alphas for ridge regression

# RNN Model Params
RNN_LAYERS: [1, 2, 3] # number of layers to try for RNN
RNN_HIDDEN_SIZE: [32, 64, 128, 256] # hidden size for RNN
RNN_DROPOUT: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7] # dropout for RNN
RNN_LR: [0.00001, 0.0001, 0.001, 0.01] # learning rate for RNN
RNN_EPOCHS: [100, 500, 1000, 10000] # number of epochs to train RNN for
RNN_BATCH_SIZE: [32, 64, 128, 256] # batch size for RNN